### Test dialogflowFirebaseFulfillment
POST http://localhost:5001/chatbot-calldesk-lcxyog/us-central1/dialogflowFirebaseFulfillment
Content-Type: application/json

{
    "queryResult":{
        "parameters": {
            "geo-city": "Marseille",
            "date": "2020-07-24"
        }
    }
}

### Test fonctionBidon
POST http://localhost:5001/chatbot-calldesk-lcxyog/us-central1/fonctionBidon
Content-Type: application/json

{
    "city": "Paris"
}

### Test fonctionBidon
POST http://localhost:5001/chatbot-calldesk-lcxyog/us-central1/fonctionBidon
Content-Type: application/json

{
    "city": "Toulouse"
}

### Test fonctionBidon
POST http://localhost:5001/chatbot-calldesk-lcxyog/us-central1/fonctionBidon
Content-Type: application/json

{
    "city": "Brest"
}